### ISSUE TITLE
Link to website in documentation is broken

### ISSUE THREAD

**Issue by Danweel** [THeK3nger/calendar-generator#8]
The link in the documentation "Readme.md" to the website that is running the generator brings you to a "Page not Found" error at https://www.davideaversa.it/experiment/calendgen/

1) Under "Build" in the .md: 
2) "The calendar generator can be accessed _following this link_."

**Comment by THeK3nger** [comment]
Thank you! I changed hosting some time ago and something must have slipped away. :) It should be solved now. We just need the time to rebuild the website. :)
